change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
exclude-labels:
  - ':tada: release'
  - ':no_entry_sign: skip'
categories:
  - title: '🚀 Features'
    label: ':star: feature'
  - title: '🐛 Bug Fixes'
    labels:
      - ':ambulance: fix'
      - ':fire: hotfix'
      - ':bug: bug'
template: |
  <!-- Before doing this release, make sure to verify the tag number -->

  ## What’s Changed

  $CHANGES
