change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
exclude-labels:
  - 'release'
  - 'skip_changelog'
template: |
  <!-- Before doing this release, make sure to verify the tag number -->

  ## What’s Changed

  $CHANGES
