name: Release Drafter

# Run on any push to main branch
# on:
#   push:
#     branches:
#       - main

# Run when a PR is closed (merged or cancelled)
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    if: "contains(github.head_ref, 'RC/')" # Skips if the merged branch does not contain the 'RC/' prefix
    steps:
      - name: Get NPM version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.package-version.outputs.current-version }}
          version: ${{ steps.package-version.outputs.current-version }}
          name: Release ${{ steps.package-version.outputs.current-version }} 🔥
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
