name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --tags
      - name: Set env
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ env.GIT_TAG }}
          name: Release ${{ env.GIT_TAG }} 🌈
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
