name: Release Drafter

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    run: |
      echo ${{github.event.pull_request.merged}}
      echo ${{github.event.pull_request.label}}
    # if: ${{ (github.event.pull_request.merged == true) && (github.event.pull_request.label == 'release') }}
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Set env
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ env.GIT_TAG }}
          version: ${{ env.GIT_TAG }}
          name: Release ${{ env.GIT_TAG }} 🔥
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
